# Generated by Django 2.2.9 on 2020-01-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
            ],
        ),
    ]
