# Generated by Django 2.2.9 on 2020-10-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Regular', 'Regular')], default='Admin', max_length=20),
        ),
    ]
